### ISSUE TITLE
[BUG] Custom Text Menu showing over Normal Beat Saber Menu

### ISSUE THREAD

**Issue by ASPNyan** [headassbtw/CustomMenuText#5]
When trying to change fonts and menu texts, the menu appears over the top of the beat saber gamemode selection and neither menus can be interacted with.

1. Click on 'Menu Text' button
2. Menu bug occurs

**Expected behavior**
Have a normal looking menu and not a bugged one

**Screenshot**
![Beat Saber 18_07_2021 7_30_00 AM](https://user-images.githubusercontent.com/85216339/126050229-4668ba61-c675-4021-ad32-3ad1fdf8ea93.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: The newest one idk

**Comment by headassbtw** [comment]
could you provide a log file?

**Comment by ASPNyan** [comment]
Log From Custom Menu Text folder: [_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835850/_latest.log)
Main Log: [_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835851/_latest.log)

**Comment by headassbtw** [comment]
looks like it's trying to select a font that isn't on the table, i'll look into this and catch the error before it causes this
i thought i fixed it, guess i didn't

**Comment by headassbtw** [comment]
[CustomMenuText.zip](https://github.com/headassbtw/CustomMenuText/files/6835868/CustomMenuText.zip)

could you try this build? i don't know what you exactly did to trigger this, so i can't reproduce it on my machine

**Comment by ASPNyan** [comment]
Nope. Cleared my .json as well and still the same error

**Comment by headassbtw** [comment]
could you send me the log?

**Comment by ASPNyan** [comment]
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835899/_latest.log)
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835900/_latest.log)

**Comment by headassbtw** [comment]
that makes even less sense than it did before.........
[try this one anyway](https://github.com/headassbtw/CustomMenuText/files/6835911/CMT.zip) (also please copy the .pdb as well, it helps me to see exactly where something breaks)

also i think one of your fonts may be broken, what files do you have in the fonts folder?

**Comment by ASPNyan** [comment]
I have the Titanfall Frontline.ttf and Calamity Regular.otf
Logs:
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835968/_latest.log)
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6835969/_latest.log)

**Comment by headassbtw** [comment]
hmm, it's the same thing as last time, and the PDB isn't doing it's job, are you sure you copied both files in the zip to your plugins folder?

**Comment by ASPNyan** [comment]
Yep. Both are in there

**Comment by headassbtw** [comment]
that's really weird, it should not be happening (pushed the changes in [this commit](https://github.com/headassbtw/CustomMenuText/commit/816049d451abdf2b27bef8d41f8ff99f233520ce)) but i guess not????

**Comment by In4init3** [comment]
im having the same issue, its overlapping the beat saber menu, none of the buttons are pressable, and i need to restart my game

**Comment by headassbtw** [comment]
cool, could you try the updated build, with `--debug` in your launch args, AND THE PDB FILE, and send me your log?

**Comment by In4init3** [comment]
it should be working now, it was an older build

**Comment by In4init3** [comment]
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6843214/_latest.log)
heres my log

**Comment by headassbtw** [comment]
the mod-specific logs tell me nothing lol, could you send over the whole game log?

**Comment by In4init3** [comment]
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6843216/_latest.log)
ok heres the whole game log

**Comment by headassbtw** [comment]
that one seems to be cut short, however you said it works now so i guess i fixed it already, i dunno

**Comment by In4init3** [comment]
i will make an image in a bit of what i see on my end with the updated dll

**Comment by In4init3** [comment]
also where do i get the .pdb
![2021-07-19](https://user-images.githubusercontent.com/82238521/126212461-c3e94651-f485-4e59-8ffc-76e332cb5585.png)

**Comment by headassbtw** [comment]
it's in the zip i posted [here](https://github.com/headassbtw/CustomMenuText/files/6835911/CMT.zip)

**Comment by In4init3** [comment]
it should've worked, but its still the same as the image before

**Comment by headassbtw** [comment]
can you send a complete log? what i mean by that is trigger the error, close the game, and then send the log

**Comment by In4init3** [comment]
here is the CMT log
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6843271/_latest.log)
and the BSIPA log
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6843277/_latest.log)

**Comment by headassbtw** [comment]
hmm alright, so it seems to be having trouble parsing some text, but i'm not exactly sure where (debug stuff isn't working on your end) so i just made it so if it does something bad, it won't load the preview, and should prevent that error

you can try [this](https://github.com/headassbtw/CustomMenuText/files/6843302/CMT.zip)

**Comment by In4init3** [comment]
it worked
![2021-07-19](https://user-images.githubusercontent.com/82238521/126214690-9825ed60-b802-422b-a7ff-6f64f7dab2e1.png)
also i modified them and my friend also added some so yeah

**Comment by headassbtw** [comment]
yea the issue was to do with entries with a length of 0, and it was trying to do some things by dividing the length, which caused it to divide by 0

**Comment by In4init3** [comment]
it works now
![2021-07-19 (5)](https://user-images.githubusercontent.com/82238521/126214957-014e4262-5dab-4667-a3cf-4501930b5964.png)

**Comment by headassbtw** [comment]
pog

**Comment by In4init3** [comment]
now you can add it as a release

**Comment by HickeyChan** [comment]
I installed Custom Menu Text 3.4.1(Hotfix), but still the menu does not work, I can not press any buttons, game version 1.16.2

I tried to delete all files associated with this mod, maybe I missed something, but the menu just does not work for me

If I missed something, tell me what to do to make the menu work, maybe delete some configs or something else, I just don't know.

All fonts are standard, I didn't change anything, just put the mod and that's it

I removed CustomMenuText.json, the problem persists

Logs attached

Sorry for my English, I don't know it. 

PC game version, Win 10 21H1

![Desktop Screenshot 2021 07 21 - 04 50 39 05](https://user-images.githubusercontent.com/87740522/126418029-72477650-ca80-4447-a0f8-2adc764f5e38.png)


[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6852293/_latest.log)
[_latest.log](https://github.com/headassbtw/CustomMenuText/files/6852295/_latest.log)
